### ISSUE TITLE
SteemCommunicationException Could not connect to the server

### ISSUE THREAD

**Issue by Tyvain** [marvin-we/steem-java-api-wrapper#207]
I use version 0.3.4 and I get this error since a few days:

eu.bittrade.libs.steemj.exceptions.SteemCommunicationException: Could not connect to the server.
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.reconnect(CommunicationHandler.java:193)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.<init>(CommunicationHandler.java:95)
        at eu.bittrade.libs.steemj.SteemApiWrapper.<init>(SteemApiWrapper.java:88)
        at leechiesnews.manager.SteemManager.executeOperation(SteemManager.java:75)
        at leechiesnews.manager.SteemManager.uploadNews(SteemManager.java:41)
        at leechiesnews.BGStorySteem.main(BGStorySteem.java:32)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
        at java.lang.Thread.run(Thread.java:748)
Caused by: javax.websocket.DeploymentException: Connection failed.
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket._connect(GrizzlyClientSocket.java:427)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.access$000(GrizzlyClientSocket.java:103)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:234)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket$1.call(GrizzlyClientSocket.java:230)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket.connect(GrizzlyClientSocket.java:248)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientContainer.openClientSocket(GrizzlyClientContainer.java:95)
        at org.glassfish.tyrus.client.ClientManager$3$1.run(ClientManager.java:668)
        at org.glassfish.tyrus.client.ClientManager$3.run(ClientManager.java:717)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.glassfish.tyrus.client.ClientManager$SameThreadExecutorService.execute(ClientManager.java:871)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:516)
        at org.glassfish.tyrus.client.ClientManager.connectToServer(ClientManager.java:360)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.reconnect(CommunicationHandler.java:189)
        ... 11 common frames omitted
Caused by: java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.glassfish.grizzly.nio.transport.TCPNIOConnectorHandler.connectAsync(TCPNIOConnectorHandler.java:137)
        at org.glassfish.grizzly.AbstractSocketConnectorHandler.connect(AbstractSocketConnectorHandler.java:91)
        at org.glassfish.grizzly.AbstractSocketConnectorHandler.connect(AbstractSocketConnectorHandler.java:79)
        at org.glassfish.tyrus.container.grizzly.client.GrizzlyClientSocket._connect(GrizzlyClientSocket.java:385)
        ... 25 common frames omitted

Do I need to update something ?

**Comment by marvin-we** [comment]
Hay @Tyvain ,

yeah - The version of SteemJ that you use connects to the websocket endpoint of Steemit.com . This has been shutdown about a week ago and now only HTTP connections are supported.

If you update to the latest SteemJ version (0.4.3) it is shipped with a HTTP connector and will connect to the newer HTTP Steem endpoint by default. 

Please let me know if this solves your issue :)
