### ISSUE TITLE
Api breakage for internal market orders, et al.

### ISSUE THREAD

**Issue by muksihs** [marvin-we/steem-java-api-wrapper#216]
Suddenly had my java bot crash with bad api responses when doing market stuff:

```
java.lang.IllegalArgumentException: Unrecognized field "order_price" (class eu.bittrade.libs.steemj.apis.market.history.model.Order), not marked as ignorable (3 known properties: "price", "steem", "sbd"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.lang.Object[0]->eu.bittrade.libs.steemj.apis.market.history.model.OrderBook["bids"]->java.util.ArrayList[0]->eu.bittrade.libs.steemj.apis.market.history.model.Order["order_price"])
        at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
        at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3676)
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleResult(JsonRPCResponse.java:164)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:124)
        at eu.bittrade.libs.steemj.apis.market.history.MarketHistoryApi.getOrderBook(MarketHistoryApi.java:146)
        at eu.bittrade.libs.steemj.SteemJ.getOrderBookUsingMarketApi(SteemJ.java:2125)
...
```

```
eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
        at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
        at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
        at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)
...
```

**Comment by muksihs** [comment]
Please use this fork for now:

https://jitpack.io/#muksihs/steem-java-api-wrapper/5b30f72
