### ISSUE TITLE
Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name

### ISSUE THREAD

**Issue by muksihs** [marvin-we/steem-java-api-wrapper#217]
```
eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
        at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
        at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
        at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
        at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)
...
```

**Comment by wonsama** [comment]
The same symptoms

15:13:21.545 [main] DEBUG eu.bittrade.libs.steemj.communication.HttpClient - Sending {"jsonrpc":"2.0","params":["login_api","get_api_by_name",["login_api"]],"id":-7385156441747590648,"method":"call"}.
15:13:23.323 [main] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Received eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse@77a98a6a[rawJsonResponse={"jsonrpc":"2.0","error":{"code":-32002,"message":"Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"json_rpc_plugin.cpp","line":206,"method":"find_api_method","hostname":"","timestamp":"2018-03-03T06:13:22"},"format":"method_itr != api_itr->second.end(): Could not find method ${method}","data":{"method":"get_api_by_name"}}]}},"id":-7385156441747590648}] 
eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
	at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
	at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
	at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
	at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
	at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
	at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)

**Comment by muksihs** [comment]
If you pull from my fork and use a local build you can get past the error, dez1337 seems to have disappeared since mid Jan, hopefully he is alright.

**Comment by muksihs** [comment]
Please use this fork for now:

https://jitpack.io/#muksihs/steem-java-api-wrapper/5b30f72

**Comment by oroger** [comment]
@muksihs I have migrated to your fork, which fixes this issue, thanks for your help !
However, I am still experiencing issues with some duplicate transactions on commenting.
Is there a dedicated place we can talk about this issue ?

Here is the error I get: 
> eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:(skip & skip_transaction_dupe_check) [...]

**Comment by harlanxh** [comment]
Exception in thread "main" eu.bittrade.libs.steemj.exceptions.SteemResponseException: Assert Exception:method_itr != api_itr->second.end(): Could not find method get_api_by_name
	at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.createThrowable(JsonRPCResponse.java:306)
	at eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse.handleError(JsonRPCResponse.java:273)
	at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:120)
	at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
	at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
	at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)
	at com.example.demo.Test.main(Test.java:50)
