### ISSUE TITLE
java.lang.IllegalArgumentException: Could not resolve type id 'create_claimed_account'

### ISSUE THREAD

**Issue by lystrosaurus** [marvin-we/steem-java-api-wrapper#228]
```java
    <dependency>
      <groupId>com.github.marvin-we.steem-java-api-wrapper</groupId>
      <artifactId>steemj-core</artifactId>
      <version>0.4.6-20180926-01PRE</version>
    </dependency>
```

```java
Map<Integer, AppliedOperation> accountHistory = steemJ
        .getAccountHistory(new AccountName("bitker001"), 100, 100);
```

```java
15:00:03.701 [main] DEBUG e.b.l.s.communication.HttpClient - Sending {"jsonrpc":"2.0","params":["database_api","get_account_history",["bitker001","100","100"]],"id":-3107385283488143642,"method":"call"}.
15:00:05.870 [main] DEBUG e.b.l.s.c.CommunicationHandler - Received eu.bittrade.libs.steemj.communication.jrpc.JsonRPCResponse@58c540cf[rawJsonResponse={"jsonrpc":"2.0","result":[[0,{"trx_id":"d6c352742dfb4d77424bdc2f66ae79eeec9f0b98","block":26645695,"trx_in_block":1,"op_in_trx":0,"virtual_op":0,"timestamp":"2018-10-09T03:29:06","op":["create_claimed_account",{"creator":"blocktrades","new_account_name":"bitker001","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6eGEmo8SqsUEHEycgqZzxEaWMi3gaaowT8PYEMFMaDfS4miDSB",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6ECkcfKUz8JDxojcA67KcjFqyrcncxkDV3RRbjziG7xRUGQ9tK",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM6XJqTPqbtW79JuLhGRnGSrmqju4oohCr3vhicMmzi16DdU7BFP",1]]},"memo_key":"STM5Y7gdh3fYTUSEBnbitrnrxGKiGaTe1cdPTY6fMHtNDVmv47a6N","json_metadata":"{}","extensions":[]}]}],[1,{"trx_id":"d6c352742dfb4d77424bdc2f66ae79eeec9f0b98","block":26645695,"trx_in_block":1,"op_in_trx":0,"virtual_op":0,"timestamp":"2018-10-09T03:29:06","op":["transfer",{"from":"blocktrades","to":"bitker001","amount":"9.297 STEEM","memo":""}]}],[2,{"trx_id":"58cd267101803a5ad44117ef465fb5eed90a63ef","block":26649323,"trx_in_block":20,"op_in_trx":0,"virtual_op":0,"timestamp":"2018-10-09T06:30:30","op":["transfer",{"from":"bitker001","to":"eric201","amount":"0.001 STEEM","memo":"测试"}]}],[3,{"trx_id":"cc9da2b65a315e6794c2a8702ccfa74a1668e5f5","block":26649405,"trx_in_block":10,"op_in_trx":0,"virtual_op":0,"timestamp":"2018-10-09T06:34:36","op":["transfer",{"from":"bitker001","to":"blocktrades","amount":"6.100 STEEM","memo":"e35f54be-9f91-437f-b7da-6694308ddecb"}]}]],"id":-3107385283488143642}] 
15:00:05.901 [main] DEBUG e.b.l.s.c.jrpc.JsonRPCResponse - The response is empty.

java.lang.IllegalArgumentException: Could not resolve type id 'create_claimed_account' into a subtype of [simple type, class eu.bittrade.libs.steemj.base.models.operations.Operation]: known type ids = [Operation, account_create, account_create_with_delegation, account_update, account_witness_proxy, account_witness_vote, author_reward, cancel_transfer_from_savings, challenge_authority, change_recovery_account, claim_reward_balance, comment, comment_benefactor_reward, comment_options, comment_payout_update, comment_reward, convert, curation_reward, custom, custom_binary, custom_json, decline_voting_rights, delegate_vesting_shares, delete_comment, escrow_approve, escrow_dispute, escrow_release, escrow_transfer, feed_publish, fill_convert_request, fill_order, fill_transfer_from_savings, fill_vesting_withdraw, hardfork, interest, limit_order_cancel, limit_order_create, limit_order_create2, liquidity_reward, pow, pow2, producer_reward, prove_authority, recover_account, report_over_production, request_account_recovery, reset_account, return_vesting_delegation, set_reset_account, set_withdraw_vesting_route, shutdown_witness, transfer, transfer_from_savings, transfer_to_savings, transfer_to_vesting, vote, withdraw_vesting, witness_update]
 at [Source: N/A; line: -1, column: -1] (through reference chain: eu.bittrade.libs.steemj.base.models.AppliedOperation["op"])

	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3589)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3530)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3518)
	at eu.bittrade.libs.steemj.SteemJ.getAccountHistory(SteemJ.java:665)
	at com.steem.api.Tests.testGetAccountHistory(Tests.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.fasterxml.jackson.databind.exc.InvalidTypeIdException: Could not resolve type id 'create_claimed_account' into a subtype of [simple type, class eu.bittrade.libs.steemj.base.models.operations.Operation]: known type ids = [Operation, account_create, account_create_with_delegation, account_update, account_witness_proxy, account_witness_vote, author_reward, cancel_transfer_from_savings, challenge_authority, change_recovery_account, claim_reward_balance, comment, comment_benefactor_reward, comment_options, comment_payout_update, comment_reward, convert, curation_reward, custom, custom_binary, custom_json, decline_voting_rights, delegate_vesting_shares, delete_comment, escrow_approve, escrow_dispute, escrow_release, escrow_transfer, feed_publish, fill_convert_request, fill_order, fill_transfer_from_savings, fill_vesting_withdraw, hardfork, interest, limit_order_cancel, limit_order_create, limit_order_create2, liquidity_reward, pow, pow2, producer_reward, prove_authority, recover_account, report_over_production, request_account_recovery, reset_account, return_vesting_delegation, set_reset_account, set_withdraw_vesting_route, shutdown_witness, transfer, transfer_from_savings, transfer_to_savings, transfer_to_vesting, vote, withdraw_vesting, witness_update]
 at [Source: N/A; line: -1, column: -1] (through reference chain: eu.bittrade.libs.steemj.base.models.AppliedOperation["op"])
	at com.fasterxml.jackson.databind.exc.InvalidTypeIdException.from(InvalidTypeIdException.java:42)
	at com.fasterxml.jackson.databind.DeserializationContext.unknownTypeIdException(DeserializationContext.java:1477)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownTypeId(DeserializationContext.java:1170)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._handleUnknownTypeId(TypeDeserializerBase.java:282)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromObject(AsArrayTypeDeserializer.java:61)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:502)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:108)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3584)
	... 27 more
```

**Comment by muksihs** [comment]
I'll take a look as soon as I can.

Did the account in question perform "create_claimed_account"?

**Comment by muksihs** [comment]
Please test using the following replacement:

compile 'com.github.muksihs.steem-java-api-wrapper:steemj-core:0.4.6-20181010-01'

**Comment by lystrosaurus** [comment]
thank you for your help
