### ISSUE TITLE
SteemJ initialization issue at init

### ISSUE THREAD

**Issue by boldrack** [marvin-we/steem-java-api-wrapper#229]
I'm getting this error during runtime ...
 
at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:86)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
        at java.net.InetAddress.getAllByName(InetAddress.java:752)
        at com.android.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:156)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:98)
        at com.android.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:345)
10-14 16:24:07.430 11049-11049/com.trender.steemsocial W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
10-14 16:24:07.431 11049-11049/com.trender.steemsocial W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
        at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:77)
10-14 16:24:07.432 11049-11049/com.trender.steemsocial W/System.err:     at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:981)
10-14 16:24:07.433 11049-11049/com.trender.steemsocial W/System.err:     at eu.bittrade.libs.steemj.communication.HttpClient.invokeAndReadResponse(HttpClient.java:47)
        at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:115)
        at eu.bittrade.libs.steemj.apis.login.LoginApi.getApiByName(LoginApi.java:107)
10-14 16:24:07.434 11049-11049/com.trender.steemsocial W/System.err:     at eu.bittrade.libs.steemj.SteemJ.getApiByName(SteemJ.java:319)
        at eu.bittrade.libs.steemj.SteemJ.<init>(SteemJ.java:157)
        at com.xscoder.steemsocial.Intro.onCreate(Intro.java:104)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
10-14 16:24:07.435 11049-11049/com.trender.steemsocial W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

------------
i'm using eu.bittrade.libs:steemj-core:0.4.3.
Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

Thanks, please help me out as i'm stuck

**Comment by michael-newsrx** [comment]
That reads like you don't have internet access enabled in your android 
permissions.

**Comment by boldrack** [comment]
Hi @michael-newsrx
Thanks for helping out ...
Actually i'm now using another branch of the lib
'com.github.marvin-we.steem-java-api-wrapper:steemj-core:0.4.x-SNAPSHOT'

upon compilation, i'm now getting this.
...
10-15 10:54:38.933 5370-5370/com.trender.steemsocial E/chromium: [ERROR:interface_registry.cc(104)] Failed to locate a binder for interface: autofill::mojom::PasswordManagerDriver
10-15 10:54:38.937 5370-5370/com.trender.steemsocial V/FA: onActivityCreated
10-15 10:54:39.091 5370-5377/com.trender.steemsocial I/art: Background partial concurrent mark sweep GC freed 2667(116KB) AllocSpace objects, 4(396KB) LOS objects, 11% free, 31MB/35MB, paused 1.388ms total 111.396ms
10-15 10:54:39.217 5370-5370/com.trender.steemsocial W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
10-15 10:54:39.231 5370-5370/com.trender.steemsocial W/System.err: eu.bittrade.crypto.core.AddressFormatException: Checksum does not validate
        at eu.bittrade.crypto.core.base58.Base58.decodeChecked(Base58.java:201)
        at eu.bittrade.crypto.core.VersionedChecksummedBytes.<init>(VersionedChecksummedBytes.java:52)
        at eu.bittrade.crypto.core.DumpedPrivateKey.<init>(DumpedPrivateKey.java:74)
        at eu.bittrade.crypto.core.DumpedPrivateKey.fromBase58(DumpedPrivateKey.java:50)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.convertWifToECKeyPair(PrivateKeyStorage.java:158)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.addPrivateKeyToAccount(PrivateKeyStorage.java:109)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.addAccount(PrivateKeyStorage.java:81)
        at com.xscoder.steemsocial.Intro.onCreate(Intro.java:107)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
10-15 10:54:39.232 5370-5370/com.trender.steemsocial W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-15 10:54:39.241 5370-5386/com.trender.steemsocial D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_previous_class(_pc)=Home, firebase_previous_id(_pi)=-4439181143517483887, firebase_screen_class(_sc)=Intro, firebase_screen_id(_si)=-4439181143517483885}]
10-15 10:54:39.296 5370-5370/com.trender.steemsocial I/Choreographer: Skipped 64 frames!  
...

**Comment by michael-newsrx** [comment]
what about the error:

Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 
support added
