### ISSUE TITLE
AddressFormatException

### ISSUE THREAD

**Issue by boldrack** [marvin-we/steem-java-api-wrapper#230]
I'm getting this error, upon initialization at runtime, this below was snipped from logcat.

10-15 15:10:58.280 6913-6913/com.trender.steemsocial W/Java7Support: Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
10-15 15:10:58.297 6913-6913/com.trender.steemsocial W/System.err: eu.bittrade.crypto.core.AddressFormatException: Checksum does not validate
        at eu.bittrade.crypto.core.base58.Base58.decodeChecked(Base58.java:201)
        at eu.bittrade.crypto.core.VersionedChecksummedBytes.<init>(VersionedChecksummedBytes.java:52)
        at eu.bittrade.crypto.core.DumpedPrivateKey.<init>(DumpedPrivateKey.java:74)
        at eu.bittrade.crypto.core.DumpedPrivateKey.fromBase58(DumpedPrivateKey.java:50)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.convertWifToECKeyPair(PrivateKeyStorage.java:158)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.addPrivateKeyToAccount(PrivateKeyStorage.java:109)
        at eu.bittrade.libs.steemj.configuration.PrivateKeyStorage.addAccount(PrivateKeyStorage.java:81)
        at com.xscoder.steemsocial.Intro.onCreate(Intro.java:118)
        at android.app.Activity.performCreate(Activity.java:6679)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
10-15 15:10:58.298 6913-6913/com.trender.steemsocial W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
------------
i'm using 
Android Studio 3.1.4
Build #AI-173.4907809, built on July 23, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 7 6.1

**Comment by michael-newsrx** [comment]
Enable Java 7

**Comment by boldrack** [comment]
Hi @michael-newsrx, thanks again.
Please, how do I enable java 7.

I couldn't pull enough information to get it done ...

**Comment by michael-newsrx** [comment]
I don't know anything about your project setup and environment.
The problem is with whatever your project setup is, not with the library.
You need to solve the error about "Java 7" not being enabled.
Until you do, anything Java 7 won't work.
