### ISSUE TITLE
Error creating a story: UnrecognizedPropertyException

### ISSUE THREAD

**Issue by Tyvain** [marvin-we/steem-java-api-wrapper#67]
Hi,

Similar error than this one: https://github.com/marvin-we/steem-java-api-wrapper/issues/36

But can't figure out how to correct it.

Code: 

```
                       CommentOperation commentOperation = new CommentOperation();
			commentOperation.setParentAuthor(new AccountName(""));
			commentOperation.setParentPermlink("");
			commentOperation.setPermlink("");
                        // same error with commentOperation.setPermlink("bitcoin-cash-wins-mining-power-as-pric-f");
			commentOperation.setJsonMetadata("{}");
			commentOperation.setAuthor(new AccountName(MY_ACCOUNT));
			commentOperation.setTitle(title);
			commentOperation.setBody(body);
```

Error:

```
09:03:40.409 [Grizzly(2)] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Raw JSON response: {"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\npermlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size.\n    {}\n    th_a  steem_evaluator.cpp:38 validate_permlink_0_1\n\n    {\"o\":{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}}\n    th_a  steem_evaluator.cpp:695 do_apply\n\n    {\"op\":[\"comment\",{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}]}\n    th_a  database.cpp:2879 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":63059,\"ref_block_prefix\":2191782717,\"expiration\":\"2017-08-22T23:02:40\",\"operations\":[[\"comment\",{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}]],\"extensions\":[],\"signatures\":[\"1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052\"]}}\n    th_a  database.cpp:2883 _apply_transaction\n\n    {\"trx\":{\"ref_block_num\":63059,\"ref_block_prefix\":2191782717,\"expiration\":\"2017-08-22T23:02:40\",\"operations\":[[\"comment\",{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}]],\"extensions\":[],\"signatures\":[\"1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052\"]}}\n    th_a  database.cpp:660 push_transaction\n\n    {\"call.method\":\"call\",\"call.params\":[\"network_broadcast_api\",\"broadcast_transaction\",[{\"operations\":[[\"comment\",{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}]],\"extensions\":[],\"ref_block_num\":63059,\"ref_block_prefix\":2191782717,\"expiration\":\"2017-08-22T23:02:40\",\"signatures\":[\"1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052\"]}]]}\n    th_a  websocket_api.cpp:124 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"steem_evaluator.cpp","line":38,"method":"validate_permlink_0_1","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size.","data":{}},{"context":{"level":"warn","file":"steem_evaluator.cpp","line":695,"method":"do_apply","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"","data":{"o":{"parent_author":"","parent_permlink":"","author":"crypcryes","permlink":"","title":"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600","body":"MY BODY","json_metadata":"{}"}}},{"context":{"level":"warn","file":"database.cpp","line":2879,"method":"_apply_transaction","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"","data":{"op":["comment",{"parent_author":"","parent_permlink":"","author":"crypcryes","permlink":"","title":"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600","body":"MY BODY","json_metadata":"{}"}]}},{"context":{"level":"warn","file":"database.cpp","line":2883,"method":"_apply_transaction","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"","data":{"trx":{"ref_block_num":63059,"ref_block_prefix":2191782717,"expiration":"2017-08-22T23:02:40","operations":[["comment",{"parent_author":"","parent_permlink":"","author":"crypcryes","permlink":"","title":"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600","body":"MY BODY","json_metadata":"{}"}]],"extensions":[],"signatures":["1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052"]}}},{"context":{"level":"warn","file":"database.cpp","line":660,"method":"push_transaction","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"","data":{"trx":{"ref_block_num":63059,"ref_block_prefix":2191782717,"expiration":"2017-08-22T23:02:40","operations":[["comment",{"parent_author":"","parent_permlink":"","author":"crypcryes","permlink":"","title":"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600","body":"MY BODY","json_metadata":"{}"}]],"extensions":[],"signatures":["1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052"]}}},{"context":{"level":"warn","file":"websocket_api.cpp","line":124,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-08-22T22:03:39"},"format":"","data":{"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction",[{"operations":[["comment",{"parent_author":"","parent_permlink":"","author":"crypcryes","permlink":"","title":"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600","body":"MY BODY","json_metadata":"{}"}]],"extensions":[],"ref_block_num":63059,"ref_block_prefix":2191782717,"expiration":"2017-08-22T23:02:40","signatures":["1b54eff6cc968761599190daf20fd4c77e87e02787f601cb59588f2dcd926a224466a55bf768dd168e91c03b6ff278593b138fc7bee3d39a9c4fdd9a27c473a052"]}]]}}]}}}
09:03:40.416 [main] DEBUG eu.bittrade.libs.steemj.communication.CommunicationHandler - Could not parse the response. Trying to transform it to an error object.
com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class eu.bittrade.libs.steemj.communication.dto.ResponseWrapperDTO), not marked as ignorable (2 known properties: "id", "result"])
 at [Source: (String)"{"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\npermlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH: Permlink is not a valid size.\n    {}\n    th_a  steem_evaluator.cpp:38 validate_permlink_0_1\n\n    {\"o\":{\"parent_author\":\"\",\"parent_permlink\":\"\",\"author\":\"crypcryes\",\"permlink\":\"\",\"title\":\"Bitcoin Cash Wins Mining Power as Price Falls Back Below $600\",\"body\":\"MY BODY\",\"json_metadata\":\"{}\"}}\n"[truncated 5373 chars]; line: 1, column: 5874] (through reference chain: eu.bittrade.libs.steemj.communication.dto.ResponseWrapperDTO["error"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:60) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:822) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1148) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1547) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1501) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:503) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1265) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:325) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4011) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2992) ~[jackson-databind-2.9.0.pr4.jar:2.9.0.pr4]
	at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:141) [steem-api-wrapper-0.3.3.jar:?]
	at eu.bittrade.libs.steemj.SteemApiWrapper.broadcastTransaction(SteemApiWrapper.java:140) [steem-api-wrapper-0.3.3.jar:?]
	at SteemJExample.main(SteemJExample.java:99) [classes/:?]
09:03:40.457 [main] ERROR SteemJExample - Error!
```

**Comment by Tyvain** [comment]
I managed to make it worked but there are still some strange problems.

My code:

```
                       CommentOperation commentOperation = new CommentOperation();
			commentOperation.setParentAuthor(new AccountName(""));
			commentOperation.setParentPermlink("bitcoin-cash-wins-mining-power-as-pric-f");			
			commentOperation.setPermlink("bitcoin-cash-wins-mining-power-as-pric-f");
			commentOperation.setAuthor(new AccountName(MY_ACCOUNT));
			commentOperation.setTitle(title);
			commentOperation.setBody(body);
			commentOperation.setJsonMetadata("{\"tags\":[\"steemit\"]}");
```

Si I had to force a non empty String in : commentOperation.setParentPermlink("bitcoin-cash-wins-mining-power-as-pric-f");	

Here is the result:

https://steemit.com/bitcoin-cash-wins-mining-power-as-pric-f/@cryptopress/bitcoin-cash-wins-mining-power-as-pric-f

Problems: 
-> the url has 2 permlinks
-> first tag is the parentPermlink... oO

**Comment by marvin-we** [comment]
Hay @Tyvain ,

thank you for creating this issue :) Actually from what I can see this is the common behavior of Steem. If we take a look at the samepl I've posted in #36 : 

```JSON
[
    [
        "comment",
        {
            "parent_author": "",
            "parent_permlink": "poetry",
            "author": "simaroy",
            "permlink": "5za2nk-an-original-bengali-poem",
            "title": "An original bengali poem:  \u09b8\u09c7\u0987 \u09b0\u09be\u09a4\u09c7\u09b0 \u09ac\u09c3\u09b7\u09cd\u099f\u09bf",
            "body": "@@ -787,17 +787,17 @@\n %E0%A6%B0 %E0%A6%AE%E0%A6%A7%E0%A7%8D%E0%A6%AF%E0%A7%87 \n-%E0%A6%AF\n+%E0%A6%98\n %E0%A6%9F%E0%A6%B2  %E0%A6%95%E0%A6%BF%E0%A6%AD%E0%A6%BE\n",
            "json_metadata": "{\"tags\":[\"poetry\",\"literature\",\"blog\",\"writing\"],\"image\":[\"https:\/\/steemitimages.com\/DQmQHX3R8ETnzKFnHMTQ9ZLbR9ZnC8dYRMEMJrFX63VCNJR\/1fbb72486206e0e47d123ad5d0160feb--rainy-mood-rainy-night.jpg\"],\"app\":\"steemit\/0.1\",\"format\":\"markdown\"}"
        }
    ]
]
```
It seems to be the common case that the parent permlink should be set to the primary tag used for this post. 

<hr>
It is planned for SteemJ 0.4.0 to implement some kind of operation helper that would allow you to do something like:

```Java
operationHelper.newPost(AccountName author, String permlink, String title, List<Tags> additionalTags, String body);
```

<hr>

The error you've reported:

> com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error"

Is caused because SteemJ is currently not able to handle errors returned by the Steem Node correctly :( This will be improved in future versions.

<hr>

Please let me know if this answers all your questions and thank you once again for reporting the issue and using SteemJ! 👍

**Comment by marvin-we** [comment]
Hay @Tyvain ,

SteemJ 0.4.0 has been released and the method I've mentioned in my last post has been added. It is also documented in [the wiki](https://github.com/marvin-we/steem-java-api-wrapper/wiki/Operations#post). Please let me know if that method works for you :) - If not, I'll reopen the ticket.

Thank you very much and best regards.
