### ISSUE TITLE
Deserialization problem in case of 'total_pow' field is -1 (Testnet)

### ISSUE THREAD

**Issue by ismelykh** [marvin-we/steem-java-api-wrapper#68]
```
Exception in thread "main" java.lang.IllegalArgumentException: Can not deserialize value of type long from String "18446744073709551615": not a valid Long value
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.util.ArrayList[0]->eu.bittrade.libs.steemj.base.models.GlobalProperties["total_pow"])
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3738)
	at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:3676)
	at eu.bittrade.libs.steemj.communication.CommunicationHandler.performRequest(CommunicationHandler.java:157)
	at eu.bittrade.libs.steemj.SteemApiWrapper.getDynamicGlobalProperties(SteemApiWrapper.java:706)
	at SteemJExample.main(SteemJExample.java:79)
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Can not deserialize value of type long from String "18446744073709551615": not a valid Long value
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.util.ArrayList[0]->eu.bittrade.libs.steemj.base.models.GlobalProperties["total_pow"])
	at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.weirdStringException(DeserializationContext.java:1504)
	at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdStringValue(DeserializationContext.java:910)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer._parseLong(NumberDeserializers.java:584)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:557)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:535)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:285)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:3733)
	... 4 more
```

**Comment by ismelykh** [comment]
I was just changing long to BigInteger, forgot to report it.
